### ISSUE TITLE
Can we move this repo?

### ISSUE THREAD

**Issue by jcoffland** [kbernhagen/fah-osx-installer#1]
I'd like to have both the contents of this repo and that of ``fah-client-osx-uninstaller`` to move to ``fah-client-bastet/install/osx``.  The Windows installer was moved similarly.  Are there any reasons it couldn't be done?

**Comment by kbernhagen** [comment]
I have a working fah-client-bastet branch which now makes a flatdistpkg installer, sans any uninstaller.

Rather than bundle the actual uninstaller, which rarely changes, I'd like to simply bundle an `uninstaller.url` file.

What do you think?

**Comment by jcoffland** [comment]
Sounds good to me.

**Comment by kbernhagen** [comment]
For uninstaller.url, I thought I'd use use
https://foldingathome.org/start-folding/

Can you eventually publish fah-uninstaller 0.1.5 (latest), and have it appear there?

Or can you suggest another url? Maybe with a #fragment?

**Comment by jcoffland** [comment]
I can add a link from there.  Does it make sense to publish OSX uninstaller releases here: https://github.com/FoldingAtHome/fah-client-osx-uninstaller?  Does it need to be signed?  Where do I find the latest?  On the build worker?

**Comment by kbernhagen** [comment]
It needs to be signed and notarized. You need to trigger macos-12-universal release worker. That will build a release uninstaller. Only the release flatdistpkg builds get notarized.

You can tag the repo ‘0.1.5’, make a release, then upload fah-uninstaller_0.1.5_all.pkg. 

The mpkg.zip is not needed. The pkg is already a compressed archive. 

The url you suggest sounds good, with /releases/ appended.

**Comment by kbernhagen** [comment]
The build product should be on the build master.

**Comment by kbernhagen** [comment]
The mpkg.zip will be on the master. Just unzip that to get the pkg.

**Comment by kbernhagen** [comment]
Please first merge new PRs for `fah-client-bastet` and `fah-client-osx-uninstaller`.

**Comment by jcoffland** [comment]
Done.

**Comment by kbernhagen** [comment]
After merging my latest PR for `fah-build` and re-creating the build master, you can

trigger `macos-12-universal-uninstaller-release`

tag and create '0.1.5' release of `fah-client-osx-uninstaller`

upload pkg to release files

/home/admin/fah-build/builds/release/fah-uninstaller/macos-12-universal/v0.1/latest/fah-uninstaller_0.1.5_all.pkg

**Comment by kbernhagen** [comment]
Note there has been another PR for `fah-client-osx-uninstaller` that goes with the `fah-build` PR. It makes cbang a submodule of the uninstaller.
